By
### Bernardo Vimpi
April 2020

#### PROJECT OBJECTIVE AND SCOPE

This project aims at analysing the concepts of Spliting the data into Train and Test. This is very important concept since it is fundametal especially when analysing overfittng and underfitting data related issues. I also explain how to go about randomizing the data and/or controlling the process in a such as way when the data is split we can have the randomized data remain consistent everytime we re-run the cells. 

### TRAIN & TEST SPLIT

#### Import relevant libraries

In [52]:
import numpy as np
from sklearn.model_selection import train_test_split

##### Let's create and generate data use for Split

In [53]:
a= np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [54]:
b=np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

#### USE TRAIN TEST SPLIT TO SPLIT THE DATA

In [55]:
train_test_split(a)

[array([33,  2, 51, 43, 92, 86,  9, 45, 37, 39, 12, 66,  1, 32, 68,  6, 87,
        98, 25, 60, 73,  3, 55, 10, 59, 65, 47, 53, 30, 22, 54, 28, 76, 83,
        17, 75, 67, 41, 34, 61, 21, 48, 70, 26, 46, 27,  5, 95, 82, 50, 84,
        88, 85, 78, 52, 64, 96, 80, 49, 57, 99, 72, 93, 56, 91,  7, 19, 11,
        69, 29, 90, 35, 42, 14, 20]),
 array([ 79,  94,  15,  24,  23,   4,  13, 100,  62,  89,  71,   8,  63,
         40,  44,  31,  38,  74,  58,  81,  77,  36,  16,  18,  97])]

#### Results:

The first array is always considered the "Training Array" while the second is the "Testing Array"

###### EXPLORING THE RESULTS

In [56]:
a_train, a_test =train_test_split(a)

In [57]:
a_train.shape, a_test.shape

((75,), (25,))

#### Result

a_train has a lenght of 75 while a_test has a lenght of 25. 

In [58]:
a_train

array([28, 74, 57, 32,  5, 89, 25, 90, 60, 92, 30, 61, 77, 78, 18, 71, 46,
       70, 93, 21,  2, 15, 86, 75, 84, 17, 14,  4, 62, 65,  7, 81, 24, 80,
       16, 20, 42, 79, 11, 35, 47, 88, 73, 67, 72, 34, 27, 40,  1, 52, 66,
       76, 49, 26, 82, 54,  8, 98, 33, 85, 39, 44, 41, 64, 63, 68, 19, 13,
       31, 48, 94, 22,  3, 83, 55])

In [59]:
a_test

array([ 59,  50,  37,  96,  56,  69,  12,  10,  97,  29,   6,  95,  58,
        53,  38,  43,  51,  45,  23,  36,  99,  91,  87,   9, 100])

#### Results 
There are two important observations here: First, the default split is 75 and 25. Second, both arrays are randomized in a non-sequential order. Third, 75, 25 is not the ideal split for the work since there is larger amount of the data being dedicated to testing. We can imporve the split by adding the testsize of 80 to 20. 

#### CHANGING THE TESTSIZE OF THE SPLIT

In [60]:
a_train, a_test =train_test_split(a,test_size=0.2)
# since the shiffle is set to True by default, we can always control it using the shuffle=False in the code as well, as needed.
# in this case it would be a_train, a_test =train_test_split(a,test_size=0.2, shuffle =False)
# since each time we re-run the sells the numbers get randomized, we can also control it to how many times the shuffled numbers remain the same.
# in this case we can add the random_state in the code like (a_train, a_test =train_test_split(a,test_size=0.2, random_state=42)


#### EXPLORING THE RESULTS

In [61]:
a_train.shape, a_test.shape

((80,), (20,))

### Results
a_train has a lenght of 80 while a_test the lenght of 20.

In [62]:
a_train

array([100,  65,  68,  72,   3,  87,  94,  81,  25,  60,  92,  27,  74,
        13,  57,   8,  20,  42,  73,  79,  26,  71,  80,  76,  77,  62,
        85,  51,   6,  63,  54,  96,  49,   2,  89,  43,  95,  91,  37,
        61,  86,  48,  31,   1,  99,  82,  90,  75,  56,  36,  67,  16,
        88,  21,   7,  35,  18,  38,  23,  30,  44,   9,  53,  58,  50,
        19,  24,  12,   5,  93,  39,  59,  98,  29,  14,  83,  52,  40,
        41,  64])

In [63]:
a_test

array([11, 10, 17, 70, 45, 55, 78, 32, 28, 47, 66, 97, 46, 33, 15, 34, 84,
       22, 69,  4])

##### SPLIT MORE THAN ONE ARRAYS AT THE SAME TIME. 

In [64]:
a_train, a_test, b_train, b_test =train_test_split(a, b, test_size=0.2)

In [65]:
a_train.shape, a_test.shape

((80,), (20,))

In [66]:
a_train

array([  8,  89,  56,  49,  72,  87,  68,   3,  60,  42,  30,  34,  82,
        10,   1,  12,  71,  48,  31,  77,  57,  53,  91,  33,  47,  22,
        85,  32,  88,  40,  79,  38,  67,   9,  75,  23,  93,  94,  73,
        29,  98,   2,   7,  90, 100,  54,  46,  64,  24,  76,  55,   6,
        52,  18,  74,  21,  16,  39,   4,  66,  96,  81,  25,  36,  27,
         5,  28,  51,  15,  20,  41,  50,  95,  78,  11,  62,  99,  58,
        65,  45])

In [67]:
a_test

array([61, 80, 84, 44, 59, 70, 97, 86, 92, 43, 35, 37, 26, 14, 69, 17, 19,
       83, 63, 13])

In [68]:
b_train.shape, b_test.shape

((80,), (20,))

In [69]:
b_train

array([508, 589, 556, 549, 572, 587, 568, 503, 560, 542, 530, 534, 582,
       510, 501, 512, 571, 548, 531, 577, 557, 553, 591, 533, 547, 522,
       585, 532, 588, 540, 579, 538, 567, 509, 575, 523, 593, 594, 573,
       529, 598, 502, 507, 590, 600, 554, 546, 564, 524, 576, 555, 506,
       552, 518, 574, 521, 516, 539, 504, 566, 596, 581, 525, 536, 527,
       505, 528, 551, 515, 520, 541, 550, 595, 578, 511, 562, 599, 558,
       565, 545])

In [70]:
b_test

array([561, 580, 584, 544, 559, 570, 597, 586, 592, 543, 535, 537, 526,
       514, 569, 517, 519, 583, 563, 513])

Thank you

### Bernardo Vimpi

April 2020